sudo: false
language: python
dist: trusty

matrix:
  include:
    # Default Python
    - env: TOXENV=flake8
    - env: TOXENV=markdown-lint
      before_install: npm install -g markdownlint-cli
    - env: TOXENV=linkchecker
    - env: TOXENV=jshint
      before_install: npm install -g jshint
    - env: TOXENV=csslint
      before_install: npm install -g csslint
    # Python version specific
    - python: '2.7'
      env: TOXENV=py27-integration
    - python: '2.7'
      env: TOXENV=py27-min-req
    - python: '2.7'
      env: TOXENV=py27-unittests
    - python: '3.4'
      env: TOXENV=py34-integration
    - python: '3.4'
      env: TOXENV=py34-min-req
    - python: '3.4'
      env: TOXENV=py34-unittests
    - python: '3.5'
      env: TOXENV=py35-integration
    - python: '3.5'
      env: TOXENV=py35-min-req
    - python: '3.5'
      env: TOXENV=py35-unittests
    - python: '3.6'
      env: TOXENV=py36-integration
    - python: '3.6'
      env: TOXENV=py36-min-req
    - python: '3.6'
      env: TOXENV=py36-unittests
    - python: '3.7'
      env: TOXENV=py37-integration
      dist: xenial
      sudo: true
    - python: '3.7'
      env: TOXENV=py37-min-req
      dist: xenial
      sudo: true
    - python: '3.7'
      env: TOXENV=py37-unittests
      dist: xenial
      sudo: true
    - python: 'pypy'
      env: TOXENV=pypy-integration
    - python: 'pypy'
      env: TOXENV=pypy-min-req
    - python: 'pypy'
      env: TOXENV=pypy-unittests
    - python: 'pypy3'
      env: TOXENV=pypy3-integration
    - python: 'pypy3'
      env: TOXENV=pypy3-min-req
    - python: 'pypy3'
      env: TOXENV=pypy3-unittests

install:
  - pip install codecov
  - pip install tox

script:
  - git clean -f -d -x
  - tox

after_success: codecov
